server:
  port: 9100
endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true
spring:
  config:
    name: greetings
  application:
    name: greetings
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      failFast: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}